name: delivery_tracker
description: A Flutter app to track deliveries by serial number and client.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobile_scanner: ^6.0.2
  sqflite: ^2.4.0
  path: ^1.9.0
  path_provider: ^2.1.3
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  audioplayers: ^6.5.0
  vibration: ^3.1.3
  excel: ^4.0.6
  pdf: ^3.11.3
  open_file: ^3.5.10
  share_plus: ^11.1.0
  connectivity_plus: ^6.1.5
  internet_connection_checker_plus: ^2.7.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/beep.wav

