// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD12HEbJt8B-rMyYvLD25iFMuqEB1R0qM',
    appId: '1:962865200276:web:39ebd3db5f4266c7068881',
    messagingSenderId: '962865200276',
    projectId: 'delivery-tracker-c6a84',
    authDomain: 'delivery-tracker-c6a84.firebaseapp.com',
    storageBucket: 'delivery-tracker-c6a84.firebasestorage.app',
    measurementId: 'G-1692SQ26PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB10eeTsUekJxypL2aEFiS9Zq0gi0SoJAs',
    appId: '1:962865200276:android:5e4f09f513421786068881',
    messagingSenderId: '962865200276',
    projectId: 'delivery-tracker-c6a84',
    storageBucket: 'delivery-tracker-c6a84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMYG5HggGzg4WvRLVy5-w01xhUEYwOtvQ',
    appId: '1:962865200276:ios:acd8e5be6d75d28a068881',
    messagingSenderId: '962865200276',
    projectId: 'delivery-tracker-c6a84',
    storageBucket: 'delivery-tracker-c6a84.firebasestorage.app',
    iosBundleId: 'com.example.deliveryTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMYG5HggGzg4WvRLVy5-w01xhUEYwOtvQ',
    appId: '1:962865200276:ios:acd8e5be6d75d28a068881',
    messagingSenderId: '962865200276',
    projectId: 'delivery-tracker-c6a84',
    storageBucket: 'delivery-tracker-c6a84.firebasestorage.app',
    iosBundleId: 'com.example.deliveryTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD12HEbJt8B-rMyYvLD25iFMuqEB1R0qM',
    appId: '1:962865200276:web:94fae3c18ae0f0dc068881',
    messagingSenderId: '962865200276',
    projectId: 'delivery-tracker-c6a84',
    authDomain: 'delivery-tracker-c6a84.firebaseapp.com',
    storageBucket: 'delivery-tracker-c6a84.firebasestorage.app',
    measurementId: 'G-SRHVVH4HMQ',
  );
}
